### ISSUE TITLE
功能请求：延迟从释放技能开始计算，而不是从原有的flytext出现开始

### ISSUE THREAD

**Issue by EtherealAO** [Bluefissure/MultiHit#1]
以战士为例，凶残裂的flytext出现时机是动画第一击命中后，而暴风斩的出现时机是动画最后一击，此时无法对暴风斩的flytext进行分割。
从释放技能开始计算延迟并覆盖原有的flytext应该可以实现更好的效果

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/MultiHit/blob/CN/README_zh.md 6.
