### ISSUE TITLE
Multihit flytext breaking on certain actions

### ISSUE THREAD

**Issue by Nerentreri** [Bluefissure/MultiHit#10]
Hey! First off thanks for your amazing work and your awesome plugin.

I recently started using some of papachins work and while testing discovered that on every preset on current dalamud version the flytext timing is totally messed up and seems to loop infinitely once it _does_ start. I have attached a log output from dalamud here, I tried several things, even recreating said skill interactions from scratch but the result is always the same even with different multihit presets, but not for every action from what I observed.

[dalamudlog.txt](https://github.com/Bluefissure/MultiHit/files/13331340/dalamudlog.txt)

**Comment by Bluefissure** [comment]
What version of Dalamud are you using? If you use newer version than 9.0.0.9 you need to use https://github.com/Bluefissure/MultiHit/releases/tag/v0.0.0.22

**Comment by Nerentreri** [comment]
Why thank you thank you, I feel pretty stupid now. I tried updating ingame but since I couldnt I just chalked it off to some dalamud weirdness. Thanks a lot!

**Comment by Bluefissure** [comment]
> Why thank you thank you, I feel pretty stupid now. I tried updating ingame but since I couldnt I just chalked it off to some dalamud weirdness. Thanks a lot!

The 0.0.0.22 is not in the repo because it's not compatible with current Dalamud 9.0.0.9, so you can only manually update by downloading from github release and load it in locally.

I'll wait until new Dalamud is released and add 0.0.0.22 to the repo, after that users can update automatically.

**Comment by Bluefissure** [comment]
> > Why thank you thank you, I feel pretty stupid now. I tried updating ingame but since I couldnt I just chalked it off to some dalamud weirdness. Thanks a lot!
> 
> The 0.0.0.22 is not in the repo because it's not compatible with current Dalamud 9.0.0.9, so you can only manually update by downloading from github release and load it in locally.
> 
> I'll wait until new Dalamud is released and add 0.0.0.22 to the repo, after that users can update automatically.

Dalamud 9.0.0.12 is released, I updated repo to Multihit 0.0.0.22 just now.

**Comment by Nerentreri** [comment]
So far from testing this extensively across all abilities, nothing weird seems to happen. Thanks for your time 
Issue is resolved :)

**Comment by Nerentreri** [comment]
Thanks for your time 
Issue is resolved :)
