### ISSUE TITLE
Delay in Fly text Numbers - Good ping

### ISSUE THREAD

**Issue by WarpedEdge** [Bluefissure/MultiHit#11]
Hi! I don't know if this is the right place, but I have been using multi-hit and what would be considered high ping? I am told 60ish ping is normal in NA servers with good latency, yet all my numbers are flying out of sync. For example on Dante's VFX the DRK move Siphon Strike which does 10 hits, the move will happen, and afterwards ill see all 10 hits rapid fire at me. I have a really good connection, and it doesn't seem like it can get lower than that. Is there something I am doing wrong?

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/MultiHit#6-why-is-the-appearance-time-of-flytext-and-the-delay-i-input-for-my-own-presets-not-consistent answers it

**Comment by yangjimzero** [comment]
please ensure you also install the "[Dante]MultHit patch=多段伤害包.ttmp2 ",and make sure this pack's prority number is higher than the VFX full pack.This pack is to adjust some skills' flytext time.

> 你好！我不知道这是不是正确的地方，但我一直在使用多重命中，什么会被认为是高 ping？我被告知 60 左右的 ping 在 NA 服务器中是正常的，具有良好的延迟，但我的所有数字都飞得不同步。例如，在但丁的视觉特效中，DRK 的移动虹吸攻击会进行 10 次命中，该移动将会发生，然后我会看到所有 10 次命中都向我快速射击。我的连接非常好，而且似乎没有比这更低的了。我做错了什么吗？

**Comment by WarpedEdge** [comment]
Issue is fixed now :) I will close this one. Did have another issue but I will make that separate.
