### ISSUE TITLE
Multiple iterations of the same skill & weird delay with custom VFX

### ISSUE THREAD

**Issue by WarpedEdge** [Bluefissure/MultiHit#14]
Hi! Quick 2 questions below:

1. I am seeing multiple of the same iterations of a skill, e.g. Spinning Edge #xxxx when creating a new multi-hit. Is there a reason for multiple of them and how do I know which one to use?

2. I used the m-hit for the ninja remake for spinning edge and it works flawlessly, but for some reason when i change the vfx from nin-remake to nier ninja, the animation is longer yes, but the fly text does not appear till the way end, even though it should start at the delay of 0. Is there a reason for this? Is this something the user needs to adjust another's VFX mod for the ttmp to start sooner?

**Comment by Bluefissure** [comment]
1. If you use `/xllog` and turn the level to Debug+, it will log out the action id when you use any actions. (remember to turn it off afterwords or your log file will be large)
2. In vfx there's also a parameter that controls the flytext delay, you should be able to change it in vfxeditor.

**Comment by WarpedEdge** [comment]
Gotcha Ill try that and get back with the results :) Hoping this would help
others as well presenting my findings and how i fixed it...if im smart
enough to fix it hah.
