### ISSUE TITLE
Certain VFX such as Magicked Prism effect not working

### ISSUE THREAD

**Issue by giammod** [Bluefissure/MultiHit#18]
Some visual effects, notably a lot of Magicked Prism visual effects don't work while the Multihit Plugin is active, some examples include Deceiver's Diamonds and Uolosapa.

**Comment by Bluefissure** [comment]
It works on my machine.

**Comment by giammod** [comment]
Did you try it with the Uolosapa Magicked Prism? When I use Uolosapa with Multihit enabled the prism doesn't display properly, specifically the birds do not appear, but when I disable the plug in  the prism works as it's supposed to.

Deceiver's diamonds seem to be working now.

**Comment by Bluefissure** [comment]
Okay it should be fixed after 0.0.0.32! Thanks for letting me know.
