### ISSUE TITLE
Multihit cause abnormal animation lock after using potions

### ISSUE THREAD

**Issue by CDragonAna** [Bluefissure/MultiHit#19]
Using Multihit will cause abnormal animation lock after using potions. After the CN version 6.51 update, enabling Multihit will cause the animation lock for potions to become similar to that of a regular ability, allowing two different potions to be used within a single GCD(2.5s).

**Comment by Bluefissure** [comment]
I don't think MultiHit does anything with animation lock, are you using any other plugins/mods together? Have you tried disabling all other plugins and mods?

**Comment by Bluefissure** [comment]
should be fixed after 0.0.0.32

**Comment by CDragonAna** [comment]
Thank you very much for fixing the bug!
谢谢獭爹，爱来自静语庄园，獭爹辛苦了



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/25/2024 22:53 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Bluefissure/MultiHit] Multihit cause abnormal animation lock after using potions (Issue #19) |

Closed #19 as completed.
