### ISSUE TITLE
Multihit doesn't work properly with animation changed Souleater.

### ISSUE THREAD

**Issue by Wizality** [Bluefissure/MultiHit#20]
When I use regular Souleater, the timing function of Multihit works perfectly, but when I changed the animation to Power Slash, for some reason the flytexts don't obey their delay settings, with all the flytext appearing right at the end of the animation. [](url)

https://github.com/Bluefissure/MultiHit/assets/167203334/b2138e63-f6e9-44ab-9158-3029d38bd959

Someone mentioned in discord that a mod affecting flytext (like namingway) could affect it, but I have no namingway change enabled for Souleater, only other attacks.

**Comment by Bluefissure** [comment]
Have you checked https://github.com/Bluefissure/MultiHit?tab=readme-ov-file#6-why-is-the-appearance-time-of-flytext-and-the-delay-i-input-for-my-own-presets-not-consistent ?

**Comment by Wizality** [comment]
In regards to checking that, I don't know how or where to mess with TMB files, and another thing is by default, the flytext speed for vanilla Souleater and the modded Souleater is different which makes me wonder if this mod is somehow messing with the flytext generation. If not, then I'm at a loss.

**Comment by Bluefissure** [comment]
> Souleater

![image](https://github.com/user-attachments/assets/3c958da7-96ff-4e44-816a-d6252751d23a)

You need to either change this in-game delay `15` to `0` in either vfxeditor or by mod to make multihit delay trigered right after the animation starts.

**Comment by Wizality** [comment]
I‏‏‎ ‎can't‏‏‎ ‎find‏‏‎ ‎the‏‏‎ ‎file‏‏‎ ‎for‏‏‎ ‎Souleater‏‏‎ ‎End

**Comment by Wizality** [comment]
I‏‏‎ ‎just‏‏‎ ‎realised‏‏‎ ‎i‏‏‎ ‎was‏‏‎ ‎in‏‏‎ ‎the‏‏‎ ‎wrong‏‏‎ ‎section.

**Comment by Wizality** [comment]
Okay‏‏‎ ‎so‏‏‎ ‎I‏‏‎ ‎changed‏‏‎ ‎the‏‏‎ ‎settings‏‏‎ ‎to‏‏‎ ‎match‏‏‎ ‎the‏‏‎ ‎image‏‏‎ ‎except‏‏‎ ‎the‏‏‎ ‎15‏‏‎ ‎is‏‏‎ ‎now‏‏‎ ‎0,‏‏‎ ‎how‏‏‎ ‎do‏‏‎ ‎I‏‏‎ ‎actually‏‏‎ ‎get‏‏‎ ‎it‏‏‎ ‎to‏‏‎ ‎take‏‏‎ ‎effect?

**Comment by Wizality** [comment]
I'm‏‏‎ ‎completely‏‏‎ ‎new‏‏‎ ‎to‏‏‎ ‎VFXeditor‏‏‎ ‎so‏‏‎ ‎I‏‏‎ ‎don't‏‏‎ ‎wanna‏‏‎ ‎press‏‏‎ ‎something‏‏‎ ‎I‏‏‎ ‎shouldn't.

**Comment by Bluefissure** [comment]
> Okay‏‏‎ ‎so‏‏‎ ‎I‏‏‎ ‎changed‏‏‎ ‎the‏‏‎ ‎settings‏‏‎ ‎to‏‏‎ ‎match‏‏‎ ‎the‏‏‎ ‎image‏‏‎ ‎except‏‏‎ ‎the‏‏‎ ‎15‏‏‎ ‎is‏‏‎ ‎now‏‏‎ ‎0,‏‏‎ ‎how‏‏‎ ‎do‏‏‎ ‎I‏‏‎ ‎actually‏‏‎ ‎get‏‏‎ ‎it‏‏‎ ‎to‏‏‎ ‎take‏‏‎ ‎effect?

you can write it back to the tmb via vfxeditor, or create a mod.

**Comment by Wizality** [comment]
And‏‏‎ ‎how‏‏‎ ‎do‏‏‎ ‎I‏‏‎ ‎actually‏‏‎ ‎do‏‏‎ ‎that,‏‏‎ ‎I‏‏‎ ‎don't‏‏‎ ‎know‏‏‎ ‎how‏‏‎ ‎to‏‏‎ ‎do‏‏‎ ‎either‏‏‎ ‎of‏‏‎ ‎those‏‏‎ ‎via‏‏‎ ‎vfxeditor.

**Comment by Wizality** [comment]
Blue?‏‏‎ ‎I‏‏‎ ‎just‏‏‎ ‎wanna‏‏‎ ‎know‏‏‎ ‎how‏‏‎ ‎to‏‏‎ ‎do‏‏‎ ‎it‏‏‎ ‎‏‏via‏‏‎ ‎VFXeditor.
