### ISSUE TITLE
Multi-hits keep the game bouncing.

### ISSUE THREAD

**Issue by sdsasdgbasd** [Bluefissure/MultiHit#21]
I'm good at games and I don't know why, but the game collapses. I want to know why.The Dalamud version is 9.1.0.14.

**Comment by Bluefissure** [comment]
I don't know what you mean by "bouncing", can you provide more info?

**Comment by sdsasdgbasd** [comment]
An error appears during the game and the game is turned off.

**Comment by Bluefissure** [comment]
It's a known issue https://github.com/Bluefissure/MultiHit/issues/22

**Comment by sdsasdgbasd** [comment]
I have a crash file, but I don't know how to upload it.

**Comment by sdsasdgbasd** [comment]
I can't upload it because the extension doesn't support it. The extension is tspack, can I change it and upload it?

**Comment by Bluefissure** [comment]
> I can't upload it because the extension doesn't support it. The extension is tspack, can I change it and upload it?

You can change it to `.zip` and upload, if you're running in CN I basically have a bug to fix, you can wait for an update.

**Comment by sdsasdgbasd** [comment]
I am doing it on KR server.

**Comment by Bluefissure** [comment]
> I am doing it on KR server.

I can only analyse CN or Intl client because I don't have a KR game client, so you don't have to try uploading your tspack again.

You can try it after the bug fix (will be released as 0.0.0.24).

**Comment by sdsasdgbasd** [comment]
Thank you. I'll be waiting for you.

**Comment by Bluefissure** [comment]
> Thank you. I'll be waiting for you.

It should be released.

**Comment by sdsasdgbasd** [comment]
I'll download the file that just came up and try it.

**Comment by sdsasdgbasd** [comment]
I was so flustered that I couldn't create the file, but the 0.0.0.24 degree game turned off.

**Comment by Bluefissure** [comment]
> I was so flustered that I couldn't create the file, but the 0.0.0.24 degree game turned off.

degree?

**Comment by sdsasdgbasd** [comment]
The game is off again. I used CN's for the plug-in.

**Comment by Bluefissure** [comment]
What did you do when the game crashed? Can you reproduce the crash?

**Comment by sdsasdgbasd** [comment]
Aloalo Isle The game turned off while playing difficulty.

**Comment by Bluefissure** [comment]
I still need a `.tspack` or the relavant log files to investigate.

**Comment by sdsasdgbasd** [comment]
I couldn't make that file when the game turned off because I was panicking.

**Comment by sdsasdgbasd** [comment]
Does the game originally turn off if I use other plug-ins or mods together?

**Comment by Bluefissure** [comment]
> Does the game originally turn off if I use other plug-ins or mods together?

I'm not sure what plugins you're using, please upload your `dalamud.log` if no tspack files were generated.

**Comment by sdsasdgbasd** [comment]
[Uploading XIVLauncher.zip…]()

**Comment by Bluefissure** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by sdsasdgbasd** [comment]
[dalamud_appcrash_20240729_221010_451_17652.zip](https://github.com/user-attachments/files/16416611/dalamud_appcrash_20240729_221010_451_17652.zip)

**Comment by Bluefissure** [comment]
Please try 0.0.0.25

**Comment by sdsasdgbasd** [comment]
ok

**Comment by sdsasdgbasd** [comment]
I think it's just my problem of playing games on the Korean server.
[crash-20240801011807.zip](https://github.com/user-attachments/files/16444673/crash-20240801011807.zip)

**Comment by Bluefissure** [comment]
Maybe that's a game bug and was fixed in 7.0, not sure. It didn't happen to intl server to me since 7.0.

**Comment by sdsasdgbasd** [comment]
Then I'll wait until 7.0. Thank you for answering all the questions I keep asking
