### ISSUE TITLE
Import/Export Tool not working

### ISSUE THREAD

**Issue by NotReallyHo** [Bluefissure/MultiHit#32]
Hi! I noticed that there was no documentation on how the import/export function, and it doesn't seem to function either.
Current workaround would be grabbing the json file located in APPDATA that's saved and then manually copy/pasting it into the existing multihit.json or replacing it entirely. 

(I might make a fork to try developing that function if that's alright with you!)

**Comment by Bluefissure** [comment]
It should work well as:
Export:
![image](https://github.com/user-attachments/assets/d4600f3f-c737-4114-81a6-e1d1c252d0d1)
Import:
![image](https://github.com/user-attachments/assets/593a1402-6ad2-45c3-b903-865e31ae4f8b)
And I don't think it needs any documentation for selecting a path/file to do the export/import?

**Comment by NotReallyHo** [comment]
I'm sorry about my horrid file structure, i'll have to redo it later
![image](https://github.com/user-attachments/assets/3eefaeac-7b33-4cf2-b96d-c089457e50f6)
![image](https://github.com/user-attachments/assets/b7282ade-843f-4080-9fb2-1754157462c5)
Also thanks for the fast reply!

**Comment by NotReallyHo** [comment]
Ah, I see the issue. Having a / in the folder name is most likely breaking the export so I'll go change the filename. Thanks for looking into this issue!
