### ISSUE TITLE
Sum of the damage percentage of hits limited to 100

### ISSUE THREAD

**Issue by Xenosaint** [Bluefissure/MultiHit#4]
The version 0.0.0.13 of MultiHit allows the sum of percentages to exceed 100, which could be a good feature since that in the feature of the original hit as final hit, MultiHit would not change the color of the original flying text, limiting the color customization.

However, it seems that the sum of the damage percentages could not exceed 100 in version 0.0.0.17. If a hit whose damage percentage with other hit percentages exceeds 100, then that hit got automatically deleted. 
I think allowing the sum to exceed 100 could be a good feature, which could create an accumulating effect for the number of damage, also allowing the player to know the exact damage a skill dealt while keeping the color customization.

I wonder if a toggle could be added in future updates for this.

**Comment by Bluefissure** [comment]
I can add a toggle for the 100% limitation as well as the custom color in final hit, but I'm a little busy these days with other plugins (CN just came to patch 6.3 and I'm maintaining the Dalamud as well).

The new feature requests may need to be on hold for several days.

**Comment by Bluefissure** [comment]
Finished in https://github.com/Bluefissure/MultiHit/releases/tag/v0.0.0.19
