### ISSUE TITLE
Multihit is hiding all flying text

### ISSUE THREAD

**Issue by rheto4** [Bluefissure/MultiHit#7]
Whenever i activate multihit, all the dmg flying text disappears.
I'm using the Nero moveset for Gunbreaker et no flying text appear no matter what i do.

**Comment by Bluefissure** [comment]
Does it still happen? Could you provide me the log? (in /xllog and switch the level to Debug+)

**Comment by rheto4** [comment]
Well, i stopped playing the game so uh… Envoyé de mon iPhoneLe 7 nov. 2023 à 18:37, Bluefissure ***@***.***> a écrit :﻿
Does it still happen? Could you provide me the log? (in /xllog and switch the level to Debug+)

**Comment by Bluefissure** [comment]
It's no problem! Enjoy other stuff irl!
I'm recently working on some optimization of this plugin and feel free to reopen this issue if you have same / other questions.
