### ISSUE TITLE
Multihit crashing FFXIV

### ISSUE THREAD

**Issue by Shrimbop** [Bluefissure/MultiHit#9]
Hi there,

I love this plugin, but every time I use it, it ends up crashing my Dalamud, which in turn ends up crashing the entire game. Any ideas on how to fix this? I'm using XIVonMac on my Macbook M2. Every other plugin seems to run fine, but this consistently crashes.

**Comment by Bluefissure** [comment]
That's a known bug and I haven't figure out a solution, there might be some configuration in the in-game flytext delay of AoE actions should be taken care of (like, cannot be 0-delay for AoE actions). You can try disable all of the AoE actions and check whether the issue persists.

**Comment by Bluefissure** [comment]
Hi! I made an update to the code performance in version 0.0.0.21, could you update and check whether it still crash the game?

**Comment by MikevLeeuwen** [comment]
After the dalamud update of today it also started causing crashes for me. After turning off only MultiHit, no crashes are being caused anymore.

**Comment by Bluefissure** [comment]
> After the dalamud update of today it also started causing crashes for me. After turning off only MultiHit, no crashes are being caused anymore.

Please wait and update MultiHit to 0.0.0.22, for more details please check https://github.com/Bluefissure/MultiHit/issues/10
